name: Update DS

on:
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Write key
        run: |
          echo '${{ secrets.MAIN }}' > compiler/ds/src/main/java/org/example/Main.java
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Download apk
        run: |
          cd compiler/ds
          chmod +x download.sh
          ./download.sh
      - name: Parse apk
        run: |
          cd compiler/ds
          ./gradlew build
          ./gradlew run
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Commit changes
        run: |
          git add simnet/utils/ds.py
          git commit -S -m ":bento: Update ds salt"
          git push
